coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
