coverage:
  precision: 2
  round: down
  range: '60...100'

  status:
    project:
      default:
        target: auto
        threshold: 5%

    patch:
      default:
        target: 50%
        threshold: 0%

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false
